version: '3.8'

services:
  api:
    container_name: betifyGG.api.prod
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=prod
    command: sh -c "npm run build && npm run prod"

  postgresdb:
    container_name: betifyGG.postgresDb.prod
  
  pgadmin:
    container_name: betifyGG.pgAdmin.prod