version: '3.8'

services:
  api:
    build:
      context: .
    restart: unless-stopped
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - postgresdb
    env_file:
      - .env

  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DBNAME
      - PGPORT=$POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./data/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  pgadmin:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile.pgAdmin
    restart: unless-stopped
    logging:
      driver: none
    depends_on:
      - postgresdb
    ports:
      - $PGADMIN_PORT:80
    user: $UID:$GID
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_USER
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - ./postgres/pgAdmin:/var/lib/pgadmin