version: '3.8'

services:
  api:
    container_name: betifyGG.api.dev
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/usr/src/app
    command: npm run dev
  
  postgresdb:
    container_name: betifyGG.postgresDb.dev

  pgadmin:
    container_name: betifyGG.pgAdmin.dev